---
title: "All Visualizations"
author: "Victor Dépré, Maxime Jacques, Alexis Chabert"
date: "11/04/2020"
output: html_document
---

<style>
.html-widget {margin: auto;}
</style>
<style>
body {text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr) 
library(tidyr)
```

```{r include = FALSE}

library(coronavirus)

df_daily <- coronavirus %>% 
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active =  confirmed - death - recovered) %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered),
                active_cum = cumsum(active))


```

---

Cumulative number of cases in the world graph



```{r echo=FALSE}

Graph1.1 <- plotly::plot_ly(df_daily, x = ~date, y = ~active_cum, name = 'Active', type = 'scatter', mode = 'none', stackgroup = 'one', fillcolor = "#1f77b4") %>%
plotly::add_trace(y = ~recovered_cum, name = 'Recovered', fillcolor = "green") %>%
plotly::add_trace(y = ~death_cum, name = "Death", fillcolor = "red") %>%
plotly::layout(title = "",
          xaxis = list(title = "",
                       showgrid = FALSE),
          yaxis = list(title = "Cumulative Number of Cases",
                       showgrid = FALSE),
          legend = list(x = 0.1, y = 0.9),
                  hovermode = "compare")


Graph1 <- plotly::plot_ly(data = df_daily,
                x = ~ date,
                y = ~ active_cum, 
                name = 'Active', 
                fillcolor = 'paleturquoise2',
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
  plotly::add_trace(y = ~ recovered_cum,
                    name = "Recovered",
                    fillcolor = 'lightgreen') %>%
  plotly::add_trace(y = ~ death_cum,
                    name = "Death",
                    fillcolor = 'lightcoral') %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")

Graph1

```




```{r include = FALSE}

library(coronavirus)

CoronavirusUK <- filter(coronavirus, Country.Region == "United Kingdom")

CoronavirusUK_daily <- CoronavirusUK %>% 
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active =  confirmed - death - recovered) %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered),
                active_cum = cumsum(active))

```

---

Cumulative number of cases in the UK graph



```{r echo=FALSE}

Graph1UK.1 <- plotly::plot_ly(CoronavirusUK_daily, x = ~date, y = ~active_cum, name = 'Active', type = 'scatter', mode = 'none', stackgroup = 'one', fillcolor = "#1f77b4") %>%
plotly::add_trace(y = ~recovered_cum, name = 'Recovered', fillcolor = "green") %>%
plotly::add_trace(y = ~death_cum, name = "Death", fillcolor = "red") %>%
plotly::layout(title = "",
          xaxis = list(title = "",
                       showgrid = FALSE),
          yaxis = list(title = "Cumulative Number of Cases",
                       showgrid = FALSE),
          legend = list(x = 0.1, y = 0.9),
                  hovermode = "compare")


Graph1UK <- plotly::plot_ly(data = CoronavirusUK_daily,
                x = ~ date,
                y = ~ active_cum, 
                name = 'Active', 
                fillcolor = 'paleturquoise2',
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
  plotly::add_trace(y = ~ recovered_cum,
                    name = "Recovered",
                    fillcolor = 'lightgreen') %>%
  plotly::add_trace(y = ~ death_cum,
                    name = "Death",
                    fillcolor = 'lightcoral') %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")

Graph1UK

```

```{r include = FALSE}

library(coronavirus)

CoronavirusFR <- filter(coronavirus, Country.Region == "France")

CoronavirusFR_daily <- CoronavirusFR %>% 
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active =  confirmed - death - recovered) %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered),
                active_cum = cumsum(active))

```

---

Cumulative number of cases in France graph



```{r echo=FALSE}

Graph1FR.1 <- plotly::plot_ly(CoronavirusFR_daily, x = ~date, y = ~active_cum, name = 'Active', type = 'scatter', mode = 'none', stackgroup = 'one', fillcolor = "#1f77b4") %>%
plotly::add_trace(y = ~recovered_cum, name = 'Recovered', fillcolor = "green") %>%
plotly::add_trace(y = ~death_cum, name = "Death", fillcolor = "red") %>%
plotly::layout(title = "",
          xaxis = list(title = "",
                       showgrid = FALSE),
          yaxis = list(title = "Cumulative Number of Cases",
                       showgrid = FALSE),
          legend = list(x = 0.1, y = 0.9),
                  hovermode = "compare")


Graph1FR <- plotly::plot_ly(data = CoronavirusFR_daily,
                x = ~ date,
                y = ~ active_cum, 
                name = 'Active', 
                fillcolor = 'paleturquoise2',
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
  plotly::add_trace(y = ~ recovered_cum,
                    name = "Recovered",
                    fillcolor = 'lightgreen') %>%
  plotly::add_trace(y = ~ death_cum,
                    name = "Death",
                    fillcolor = 'lightcoral') %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")

Graph1FR

```


```{r include = FALSE}

library(coronavirus)

CoronavirusIT <- filter(coronavirus, Country.Region == "Italy")

CoronavirusIT_daily <- CoronavirusIT %>% 
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active =  confirmed - death - recovered) %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered),
                active_cum = cumsum(active))

```

---

Cumulative number of cases in Italy graph



```{r echo=FALSE}

Graph1IT.1 <- plotly::plot_ly(CoronavirusIT_daily, x = ~date, y = ~active_cum, name = 'Active', type = 'scatter', mode = 'none', stackgroup = 'one', fillcolor = "#1f77b4") %>%
plotly::add_trace(y = ~recovered_cum, name = 'Recovered', fillcolor = "green") %>%
plotly::add_trace(y = ~death_cum, name = "Death", fillcolor = "red") %>%
plotly::layout(title = "",
          xaxis = list(title = "",
                       showgrid = FALSE),
          yaxis = list(title = "Cumulative Number of Cases",
                       showgrid = FALSE),
          legend = list(x = 0.1, y = 0.9),
                  hovermode = "compare")


Graph1IT <- plotly::plot_ly(data = CoronavirusIT_daily,
                x = ~ date,
                y = ~ active_cum, 
                name = 'Active', 
                fillcolor = 'paleturquoise2',
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
  plotly::add_trace(y = ~ recovered_cum,
                    name = "Recovered",
                    fillcolor = 'lightgreen') %>%
  plotly::add_trace(y = ~ death_cum,
                    name = "Death",
                    fillcolor = 'lightcoral') %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")

Graph1IT

```

```{r include = FALSE}

library(coronavirus)

CoronavirusUS <- filter(coronavirus, Country.Region == "US")

CoronavirusUS_daily <- CoronavirusUS %>% 
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active =  confirmed - death - recovered) %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered),
                active_cum = cumsum(active))

```

---

Cumulative number of cases in the United States graph



```{r echo=FALSE}

Graph1US.1 <- plotly::plot_ly(CoronavirusUS_daily, x = ~date, y = ~active_cum, name = 'Active', type = 'scatter', mode = 'none', stackgroup = 'one', fillcolor = "#1f77b4") %>%
plotly::add_trace(y = ~recovered_cum, name = 'Recovered', fillcolor = "green") %>%
plotly::add_trace(y = ~death_cum, name = "Death", fillcolor = "red") %>%
plotly::layout(title = "",
          xaxis = list(title = "",
                       showgrid = FALSE),
          yaxis = list(title = "Cumulative Number of Cases",
                       showgrid = FALSE),
          legend = list(x = 0.1, y = 0.9),
                  hovermode = "compare")


Graph1US <- plotly::plot_ly(data = CoronavirusUS_daily,
                x = ~ date,
                y = ~ active_cum, 
                name = 'Active', 
                fillcolor = 'paleturquoise2',
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
  plotly::add_trace(y = ~ recovered_cum,
                    name = "Recovered",
                    fillcolor = 'lightgreen') %>%
  plotly::add_trace(y = ~ death_cum,
                    name = "Death",
                    fillcolor = 'lightcoral') %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")

Graph1US

```

```{r include = FALSE}

library(coronavirus)

CoronavirusGER <- filter(coronavirus, Country.Region == "Germany")

CoronavirusGER_daily <- CoronavirusGER %>% 
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active =  confirmed - death - recovered) %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered),
                active_cum = cumsum(active))

```


---

Cumulative number of cases in Germany graph


```{r echo=FALSE}

Graph1GER.1 <- plotly::plot_ly(CoronavirusGER_daily, x = ~date, y = ~active_cum, name = 'Active', type = 'scatter', mode = 'none', stackgroup = 'one', fillcolor = "#1f77b4") %>%
plotly::add_trace(y = ~recovered_cum, name = 'Recovered', fillcolor = "green") %>%
plotly::add_trace(y = ~death_cum, name = "Death", fillcolor = "red") %>%
plotly::layout(title = "",
          xaxis = list(title = "",
                       showgrid = FALSE),
          yaxis = list(title = "Cumulative Number of Cases",
                       showgrid = FALSE),
          legend = list(x = 0.1, y = 0.9),
                  hovermode = "compare")


Graph1GER <- plotly::plot_ly(data = CoronavirusGER_daily,
                x = ~ date,
                y = ~ active_cum, 
                name = 'Active', 
                fillcolor = 'paleturquoise2',
                type = 'scatter',
                mode = 'none', 
                stackgroup = 'one') %>%
  plotly::add_trace(y = ~ recovered_cum,
                    name = "Recovered",
                    fillcolor = 'lightgreen') %>%
  plotly::add_trace(y = ~ death_cum,
                    name = "Death",
                    fillcolor = 'lightcoral') %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")

Graph1GER

```

-----

Today new cases 


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(coronavirus)
max_date <- max(coronavirus$date)
Graph2 <- coronavirus %>%
  dplyr::filter(type == "confirmed", date == max_date) %>%
  dplyr::group_by(Country.Region) %>%
  dplyr::summarise(total_cases = sum(cases)) %>%
  dplyr::arrange(-total_cases) %>%
  dplyr::mutate(country = factor(Country.Region, levels = Country.Region)) %>%
  dplyr::ungroup() %>%
  dplyr::top_n(n = 15, wt = total_cases) %>%
  plotly::plot_ly(x = ~ country,
                  y = ~ total_cases,
                  text = ~ total_cases,
                  textposition = 'auto',
                  type = "bar") %>%
  plotly::layout(yaxis = list(title = "Number of Cases"),
                 xaxis = list(title = ""),
                 margin =  list(
                   l = 10,
                   r = 10,
                   b = 10,
                   t = 10,
                   pad = 2
                 ))
Graph2

```





